version: '3.6'

services:
  api:
    build:
      context: .
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      APP_SECRET: ${APP_SECRET}
      SENDER_EMAIL: ${SENDER_EMAIL}
      SENDER_EMAIL_PASS: ${SENDER_EMAIL_PASS}
    depends_on:
      - db
    networks:
      - default
    ports:
      - 5000:80
    volumes:
      - user_files:/app/user_files
    restart: on-failure

  db:
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  user_files:
  postgres-data: